data:
    name: 'patches_dataset'
    dataset: 'hpatches'  # 'coco' 'hpatches'
    alteration: 'all'  # 'all' 'i' 'v'
    preprocessing:
        resize: [240, 320]  # [240, 320] for HPatches and False for coco
#        resize: [480, 640]  # [240, 320] for HPatches and False for coco
    # labels: magicpoint_synth20_homoAdapt100_coco/predictions # for coco

front_end_model: 'Val_model_heatmap'  # 'Train_model_frontend'
model:
    # name: 'magic_point'
    name: 'SuperPointNet_gauss2' # SuperPointNet_heatmap
    params: {
    }

    # learning_rate: 0.0001 # 0.0001
    detection_threshold: 0.015 # 0.015

    batch_size: 1
    eval_batch_size: 1
    # output parameters
    learning_rate: 0.001
    detection_threshold: 0.015 # 0.001
    nms: 4
    top_k: 1000
    nn_thresh: 1.0 # 0.7
    homography_adaptation:
        num: 0
    subpixel: 
        enable: true
        patch_size: 5
    rand_noise:
        enable: false
        sigma: 0.2
    # pretrained: 'logs/magicPoint_200000.pth.tar'
    # pretrained: 'logs/superPointNet_50000_smallKITTI.pth.tar'
    # pretrained: 'logs/superPointNet_170000_smallKITTI.pth.tar'
    # pretrained: 'logs/superPointNet_50000_fullKITTI.pth.tar'
    pretrained: 'logs/superPointNet_170000_fullKITTI.pth.tar'
    # pretrained: 'logs/superPointNet_154000_fullKITTI.pth.tar'
    # pretrained: 'logs/superPointNet_50000_bestKITTI.pth.tar'
    # pretrained: 'logs/superPointNet_170000_bestCOCO.pth.tar'
    # pretrained: 'logs/magicPoint_100000.pth.tar'


eval_iter: 1000
